apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-deployment
  labels:
    app: hotel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel
  template:
    metadata:
      labels:
        app: hotel
    spec:
      containers:
        - name: hotel
          image: xsrkt26/wangwang:hotel-latest
          ports:
            - containerPort: 8081
