apiVersion: v1
kind: Service
metadata:
  name: hotel-service
  labels:
    app: hotel
spec:
  selector:
    app: hotel
  ports:
    - protocol: TCP
      port: 80          # Service暴露的端口
      targetPort: 8080  # hotel容器内的端口
  type: ClusterIP      # 默认类型，服务只在集群内部可访问
